require "http/client"
require "http/formdata"
require "json"
require "openssl"
require "uri"
require "./config"
require "./auth"

module RightDesk
  # Thin HTTP wrapper: injects the Bearer token, targets BASE_URL, returns a
  # tiny Response the commands can branch on. Kept minimal on purpose — the
  # commands own their own JSON shaping/output.
  #
  # Failure policy: this module never raises for an expected failure. A missing token,
  # a refused connection and a timeout all come back as a Response with a status the
  # caller can branch on (401, or CONNECTION_FAILED_STATUS), so commands only ever need
  # one code path. That also lets a polling loop count consecutive failures without
  # wrapping every call in a rescue.
  module Client
    # Without these a hung socket blocks forever: HTTP::Client.exec takes no timeout, so
    # a stalled connection used to wedge the command with no output and no way out but
    # Ctrl-C. Uploads and polling loops make that a real failure mode rather than a
    # theoretical one.
    CONNECT_TIMEOUT = 10.seconds
    READ_TIMEOUT    = 60.seconds
    # A multipart body can be tens of megabytes on a slow uplink.
    UPLOAD_READ_TIMEOUT = 300.seconds

    # Not a real HTTP status. Synthesized when the request never completed, so callers
    # branch on a Response instead of rescuing. 599 is outside the registered range and
    # falls through `status_for` to exit code 1 (general failure), which is correct.
    CONNECTION_FAILED_STATUS = 599

    record Response, status : Int32, body : String do
      def success? : Bool
        status >= 200 && status < 300
      end
    end

    # `query` is an already-encoded query string (e.g. from `URI::Params.build`).
    def self.get(path : String, query : String? = nil) : Response
      request("GET", path, query: query)
    end

    def self.post(path : String, body : String? = nil) : Response
      request("POST", path, body: body)
    end

    def self.patch(path : String, body : String? = nil) : Response
      request("PATCH", path, body: body)
    end

    def self.delete(path : String) : Response
      request("DELETE", path)
    end

    # multipart/form-data upload. `fields` are plain form values; the file is sent as
    # `file_field`. `data` takes Bytes or an IO as well as a String, because a CSV
    # exported from Excel is often CP932 or Latin-1 — the server sniffs the encoding, so
    # the bytes must travel untouched.
    #
    # The body is built into a temp file rather than a String: a 25 MB upload would
    # otherwise sit in memory twice over (the file contents, then the assembled body).
    # HTTP::Client#exec accepts an IO body (BodyType = String | Bytes | IO | Nil), so it
    # streams from disk to the socket and peak memory is just the copy buffer.
    def self.post_multipart(path : String, fields : Hash(String, String),
                            file_field : String, filename : String,
                            content_type : String, data : String | Bytes | IO) : Response
      tempfile = File.tempfile("rd-upload", ".multipart")

      begin
        header = write_multipart_body(tempfile, fields, file_field, filename, content_type, data)
        tempfile.flush
        tempfile.rewind

        request("POST", path, body: tempfile, content_type: header,
          read_timeout: UPLOAD_READ_TIMEOUT)
      ensure
        tempfile.close
        tempfile.delete
      end
    end

    # Writes the multipart body into `io` and returns the Content-Type header that
    # describes it (the boundary is generated by the builder, so the two cannot disagree).
    # Separate from post_multipart so a spec can assert on the bytes it produces.
    def self.write_multipart_body(io : IO, fields : Hash(String, String),
                                  file_field : String, filename : String,
                                  content_type : String, data : String | Bytes | IO) : String
      builder = HTTP::FormData::Builder.new(io)
      fields.each { |name, value| builder.field(name, value) }
      builder.file(
        file_field,
        data.is_a?(IO) ? data : IO::Memory.new(data),
        HTTP::FormData::FileMetadata.new(filename: filename),
        HTTP::Headers{"Content-Type" => content_type}
      )
      builder.finish
      builder.content_type
    end

    private def self.request(method : String, path : String,
                             query : String? = nil, body : HTTP::Client::BodyType = nil,
                             content_type : String? = nil,
                             read_timeout : Time::Span = READ_TIMEOUT) : Response
      # No local token → synthesize a 401 so callers take the normal auth-failure
      # path (exit code 3, "run rd login") instead of raising.
      token = RightDesk::Auth.token
      unless token
        return Response.new(401, %({"error":"Not authenticated","code":"missing_token"}))
      end

      uri = URI.parse("#{RightDesk::Config.base_url}#{path}")
      uri.query = query if query && !query.empty?

      headers = HTTP::Headers{"Authorization" => "Bearer #{token}"}
      headers["Content-Type"] = content_type || "application/json" if body

      client = HTTP::Client.new(uri)
      client.connect_timeout = CONNECT_TIMEOUT
      client.read_timeout = read_timeout

      begin
        response = client.exec(method, uri.request_target, headers: headers, body: body)
        Response.new(response.status_code, response.body)
      rescue ex : IO::Error | OpenSSL::Error
        # IO::Error covers IO::TimeoutError, Socket::ConnectError and DNS failures.
        connection_failed(ex)
      ensure
        client.close
      end
    end

    private def self.connection_failed(ex : Exception) : Response
      Response.new(CONNECTION_FAILED_STATUS, {
        "error"   => "Could not reach #{RightDesk::Config.base_url}",
        "code"    => "connection_failed",
        "message" => ex.message || ex.class.name,
      }.to_json)
    end
  end
end
